### ISSUE TITLE
AltPowerBar Element

### ISSUE THREAD

**Issue by tombell** [haste/oUF#246]
I'd just like some confirmation whether this element on the boss unit frame is the `AltPowerBar` element in oUF.

![alt](https://cloud.githubusercontent.com/assets/129327/6315478/13af4b2e-b9fb-11e4-81d6-acd1f3c0e434.png)

**Comment by Rainrider** [comment]
How would one be able to tell this for certain?

However, oUF does nothing by itself. Do you have a layout installed? Does /fstack provide some usefull feedback? It you have a layout, does disabling it make the bar disappear? If yes, then just search for `.AltPowerBar` in the layout code to find out what they coded.

And, if you would excuse me pointing this out, this is the issue tracker of the oUF repo. It is not "what UI is this" thread on mmo-champion or wowinterface.

**Comment by tombell** [comment]
I was asking if the element `AltPowerBar` provided by oUF is that element of the default UI.

**Comment by Rainrider** [comment]
On the screenshot, I see a power bar. If it holds the power or the altpower of the unit it displays, I can't tell. However oUF's altpower element has a fallback option for displaying power if altpower is not present.

Now that #245 has been such an inspiration for both of us, may I point you to the wowinterface forums where oUF has a featured section dedicated to questions like that. Here is the link: http://www.wowinterface.com/forums/forumdisplay.php?f=87

**Comment by tombell** [comment]
Sorry but you've completely misunderstood my question.

I've posted a screenshot of the default boss frame. It has the encounter bar (the orange bar to the left). My question is, is **that** bar the equivalent element that `AltPowerBar` the element within oUF or not. So I know if `AltPowerBar` is what I need to add to my layout.

I have no idea why you've linked an issue completely unrelated to my question. I don't need "teaching" how to ask questions and where to ask questions. My question is regarding oUF, so I will ask it here. If *you* don't like that, you're free to ignore my question. GitHub issues aren't limited to "reporting bugs".

**Comment by Rainrider** [comment]
Oh, so instead of asking "is there an oUF element covering the encounter bar", you posted a screenshot of something, asking what is this thing ON it (and by ON you meant LEFT TO, which I figured out, but then you got me all confused by insisting on altpower)? So, I still think I told you what the altpower element does and I don't know what the encounter bar does, but you already said that telling you what I don't know is irrelevant information to you, which I fully understand and acknowledge.

Please excuse my reaction to your question and my wish to point you to a medium, where you would have reached broader and more knowledgeable auditorium. I do sincerity regret having tried and it is absolutely not my right to "teach" you how and where to ask questions. It is just that I, as someone who also has a personal oUF layout, and is interested in it's development, am watching the project on github, which translates to me receiving an email whenever someone opens an issue, which in turn lead to me getting a push notification on my mobile phone. I am not doing this for what you posted and I will surely correct this on my side.

Thank you for reading and, well, for your screenshot.

**Comment by Noixion** [comment]
Rainrider i have no clue why you used my issue for this one. but ok.

**Comment by haste** [comment]
Yes, the bar in your screenshot is the same as oUF's AltPowerBar.
